# This template will gather all the logs of a mac agent from a given starting poing in time
# to a given end point. The template also takes the path for the file where the logs will be written.
#

parameters:

- name: workingDirectory
  type: string
  default: ''

- name: outputPath 
  type: string 
  default: 'agent-logs.log'

- name: predicate
  type: string
  default: ''

- name: style
  type: string
  default: 'compact'
  values:
  - default
  - compact
  - json
  - syslog

- name: uploadLogs
  type: boolean
  default: true

- name: uploadPrefix
  type: string
  default: '$(MaciosUploadPrefix)'

- name: use1ES
  type: boolean
  default: false

steps:

- pwsh: >-
    $(System.DefaultWorkingDirectory)/$(BUILD_REPOSITORY_TITLE)/tools/devops/automation/scripts/generate_agent_logs.ps1
    -VstsToken "$(System.AccessToken)"
    -Style "${{ parameters.style }}"
    -Output "${{ parameters.outputPath }}"
    -Predicate "${{ parameters.predicate }}"
  displayName: 'Gathering agent logs'
  condition: always()
  continueOnError: true
  ${{ if ne(parameters.workingDirectory, '') }}:
    workingDirectory: ${{ parameters.workingDirectory }}

# only upload when told so
- ${{ if eq(parameters.uploadLogs, true) }}:
  - template: ../common/publish-pipeline-artifact.yml
    parameters:
      use1ES: ${{ parameters.use1ES }}
      displayName: 'Publish Artifact: Agent logs'
      condition: always()
      ${{ if eq(parameters.workingDirectory, '') }}:
        path: ${{ parameters.outputPath }}
      ${{ else }}:
        path: ${{ parameters.workingDirectory }}/${{ parameters.outputPath }}
      artifact: '${{ parameters.uploadPrefix }}$(Agent.Name)-$(System.JobName)-$(System.JobId)-${{ parameters.outputPath }}'
      continueOnError: true
